version: "3"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
      - ./requirements/bonus/website/tools/site:/var/www/html/site
      - adminer:/var/www/html/adminer
    restart: always
    depends_on:
      - wordpress
      - adminer
      - portainer
    networks:
      - InceptionNetwork
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - InceptionNetwork

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    environment:
      WP_HOST: ${WP_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_USER_ADMIN: ${WP_USER_ADMIN}
      WP_PASSWORD_ADMIN: ${WP_PASSWORD_ADMIN}
      WP_EMAIL_ADMIN: ${WP_EMAIL_ADMIN}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
    depends_on:
      - mariadb
    networks:
      - InceptionNetwork
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - 8080:8080
    restart: always
    volumes:
      - adminer:/var/www/html/adminer
    depends_on:
      - mariadb
    networks:
      - InceptionNetwork
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    ports:
      - 8000:8000
    restart: always
    networks:
      - InceptionNetwork
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  InceptionNetwork:
    driver: bridge

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/mkhairou/data/wp
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/mkhairou/data/db
  adminer:
    driver_opts:
      type: none
      o: bind
      device: /home/mkhairou/data/adminer
  portainer:
    driver_opts:
      type: none
      o: bind
      device: /home/mkhairou/data/portainer
